RFdiffusion
dockerfile
FROM nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
  && sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && apt-get -q update \ 
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  git \
  vim \
  wget \
  python3.9 \
  python3-pip \
  python-is-python3 \
  && git clone https://ghproxy.com/https://github.com/RosettaCommons/RFdiffusion.git \
  && mkdir ./RFdiffusion/rfdiffusion/models	\
  && sed -i 's|https://github.com|https://ghproxy.com/https://github.com|g' ./RFdiffusion/env/SE3nv.yml \
  && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
  && python3.9 -m pip install -q -U --no-cache-dir pip \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get autoremove -y \
  && apt-get clean \
  && pip install -q --no-cache-dir \
  dgl==1.0.2+cu116 -f https://data.dgl.ai/wheels/cu116/repo.html \
  torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 \
  e3nn==0.3.3 \
  wandb==0.12.0 \
  pynvml==11.0.0 \
  git+https://ghproxy.com/https://github.com/NVIDIA/dllogger#egg=dllogger \
  decorator==5.1.0 \
  hydra-core==1.3.2 \
  pyrsistent==0.19.3 \
  jupyterlab \
  ./RFdiffusion/env/SE3Transformer \
  && pip install --no-cache-dir ./RFdiffusion --no-deps \
  && ln -s ./RFdiffusion/rfdiffusion/models /usr/local/lib/python3.8/dist-packages/models

ENV DGLBACKEND="pytorch"

ENTRYPOINT ["jupyter-lab", "--no-browser", "--ip='0.0.0.0'", "--allow-root"]
## build & deploy 

``` bash
sudo docker build -t rfdiffusion .
sudo docker run --name rfdiffusion-gpu --gpus all -p 9901:8888 -d rfdiffusion:latest  
